base="seqNum:int*, eventId:int*, eventTimestamp:dt*"    

event_schemas={
    3: "commandedBasalRate:float, baseBasalRate:float, maxBasalRate:float, IDP:int, changeTypeRate:int",
    4: "alertIdRaw:int, alertString:str, faultLocatorData:int, param1:int, param2:float",
    5: "alarmIdRaw:int, alarmString:str, faultLocatorData:int, param1:int, param2: float",
    6: "malfidRaw:int, faultLocatorData:int, param1:int, param2:float",
    11: "presuspendState:int, insulinAmount:int, suspendReasonRaw:int, rpaTimeout:int",
    12: "preresumeState:int, insulinAmount:int",
    13: "timePrior:int, timeAfter:int, rawRtcTime:int",
    14: "datePrior:int, dateAfer:int, rawRtcTime:int",
    16: "selectedIobRaw:int, BG:int, bgEntryTypeRaw: int, IOB:int, targetBG:int, ISF:int, bgSourceTypeRaw:int, cgmCalibrationRaw:int",
    20: "completionStatusRaw:int, bolusID:int, insulinDelivered:float, insulinRequested:float, IOB:float",
    21: "completionStatusRaw:int, bolusID:int, insulinDelivered:float, insulinRequested:float, IOB:float",
    26: "alertIdRaw, faultLocatorData:int",
    28: "alarmIdRaw:int",
    33: "insulinVolume:int, v2Volume:float",
    53: "msecsincereset:int, lipoCurrent, lipoAbc:int, lipoIbc:int, lipoRemcap:int, lipoMv:int",
    55: "selectedIobRaw:int, bolusId:int, IOB:float, bolussize:float",
    59: "selectedIobRaw:int, IOB:float, bolexSize:float",
    60: "block:int, reason:int",
    61: "primeSize:float, completionStatusRaw:int",
    63: "primeSize:float, completionStatusRaw:int, position:int",
    64: "bolusId:int, bolusTypeRaw:int, correctionBolusIncludedRaw:int, carbAmount:int, BG:int, carbRatioRaw:int, IOB:float",
    65: "selectedIobRaw:int, bolusId:int, optionsRaw:int, standardPercent:int, duration:int, ISF:int, targetBg:int, userOverrideRaw:int, declinedCorrectionRaw:int",
    66: "bolusId:int: foodBolusSize:float, correctionBolusSize:float, totalBolusSize:float",
    90: "commandedBasalRate:float, featuresBitmask:int, featureBitmaskIndex:int",
    99: "version:int, configABits:int, configBBits:int, numLogEntries:int",
    140: "FMR:int, PGV:int, fmrStatusRaw:int, pgvValidRaw:int, ruleStateRaw:int, hominStateRaw:int, statusRaw:int",
    171: "dAlertIdRaw:int, faultLocatorData:int, param1:int, param2:float",
    172: "dAlertIdRaw:int",
    191: "version:int, configABits:int, configBBits:int, armcrc:int",
    203: "swUpdateStatus:int, metadataAndVersionStatus:int, fulldlandcrcStatus:int, filedlandSideLoadStatus:int, externalFlashStatus:int, updateSuccessFulRaw:int, swPartNum:int",
    212: "currentTransmitterTime:int, sessionStartTime:int, sessionDuration:int",
    213: "currentTransmitterTime:int, sessionStartTime:int, SessionDuration:int, sessionJoinReasonRaw:int",
    214: "currentTransmitterTime:int, sessionStartTime:int, sessionStopTime:int, sessionDuration:int, sessionStopReasonRaw:int",
    229: "exerciseChoiceRaw:int, exerciseTime:int, currentUserModeRaw:int, previousUserModeRaw:int, requestedActionRaw:int, sleepStartedByGuiRaw:int, exerciseStoppedByTimerRaw:int, eatingSoonStoppedByTimerRaw:int",
    230: "currentPcmRaw:int, previousPcmRaw:int, pumpSuspendedRaw:int, calculationAvailableRaw:int, cgmAvailableRaw:int, closedLoopPreferredRaw:int, sufficientClosedLoopParamsRaw:int",
    256: "glucoseValueStatusRaw:int, cgmDataTypeRaw:int, rateRaw:int, algorithmState:int, RSSI:int, currentGlucoseDisplayValue:int, egvTimestamp:int, egvInfoBitmaskRaw:int, interval:int",
    279: "commandedRateSourceRaw:int, commandedRate:int, profileBasalRate:int, algorithmRate:int, tempRate:int",
    280: "bolusId:int, bolusDeliveryStatusRaw:int, bolusTypeRaw:int, bolusSourceRaw:int, remoteId:int, requestedNow:int, requestedLater:int, extendedDurationRequested:int, deliveredTotal:int, correction:int",
    307: "armPartNumber:int, armSwVersion:int, blePartNumber:int, bleSwVersion:int",
    313: "userModeRaw:int, sensorTypeRaw:int",
    369: "dAlertIdRaw:int, sensorTypeRaw:int, faultLocatorData:int, param1:int, param2:float",
    370: "dAlertIdRaw:int, sensorTypeRaw:int",
    371: "dAlertIdRaw:int, sensorTypeRaw:int, ackSourceRaw:int",
    372: "glucoseValueStatusRaw:int, cgmDataTypeRaw:int, rateRaw:int, algorithmStateRaw:int, RSSI:int, currentGlucoseDIsplayValue:int, egvTimestamp:int, egvInfoBitmaskRaw:int, interval:int",
    394: "cgmTimestamp:int, sessionSignature:int",
    399: "glucoseValueStatusRaw:int, cgmDataTypeRaw:int, rateRaw:int, algorithmStateRaw:int, RSSI:int, currentGlucoseDisplayValue:int, egvTimestamp:int, egvInfoBitmaskRaw:int, interval:int",
    404: "sessionStartTime:int, sessionDuration:int",
    405: "currentTransmitterTime:int, sessionStartTime:int, sessionStopTime:int, sessionDuratin:int, sessionStopReason:int, stopSessionCode:int",
    406: "sessionStartTime:int, sessionJointTime:int, sessionDuration:int, sessionJoinReason:int",
    447: "currentTransmitterTime:int, sessionStartTime:int, sessionStopTime:int, sessionDuration:int, sessionStopReason:int, sessionStopReason:int, stopSessionCode:int",
    460: "dAlertIdRaw:int, sensorTypeRaw:int, faultLocatorData:int, param1:int, param2:float",
    461: "dAlertIdRaw:int, sensorTypeRaw:int",
    81: "dailyTotalBasal:float, lastBasalRate:float, IOB:float, batteryChargePercentMsbRaw:int, batteryChargePercentLsbRaw:int, batteryLipomillivolts:int",
    48: "carbs:float",
    36: "negotiatedCurrent:float",
    37: "negotiatedCurrent:float"}


EVENT_IDS = {
    3: "LidBasalRateChange",
    4: "LidAlertActivated",
    5: "LidAlarmActivated",
    6: "LidMalfunctionActivated",
    11: "LidPumpingSuspended",
    12: "LidPumpingResumed",
    13: "LidTimeChanged",
    14: "LidDateChanged",
    16: "LidBgReadingTaken",
    20: "LidBolusCompleted",
    21: "LidBolexCompleted",
    26: "LidAlertCleared",
    28: "LidAlarmCleared",
    33: "LidCartridgeFilled",
    53: "LidShelfMode",
    55: "LidBolusActivated",
    59: "LidBolexActivated",
    60: "LidDataLogCorruption",
    61: "LidCannulaFilled",
    63: "LidTubingFilled",
    64: "LidBolusRequestedMsg1",
    65: "LidBolusRequestedMsg2",
    66: "LidBolusRequestedMsg3",
    90: "LidNewDay",
    99: "LidArmInit",
    140: "LidPlgsPeriodic",
    171: "LidCgmAlertActivated",
    172: "LidCgmAlertCleared",
    191: "LidVersionInfo",
    203: "LidUpdateStatus",
    212: "LidCgmStartSessionGx",
    213: "LidCgmJoinSessionGx",
    214: "LidCgmStopSessionGx",
    229: "LidAaUserModeChange",
    230: "LidAaPcmChange",
    256: "LidCgmDataGxb",
    279: "LidBasalDelivery",
    280: "LidBolusDelivery",
    307: "LidVersionsA",
    313: "LidAaDailyStatus",
    369: "LidCgmAlertActivatedDex",
    370: "LidCgmAlertClearedDex",
    371: "LidCgmAlertAckDex",
    372: "LidCgmDataFsl2",
    394: "LidCgmJoinSessionG7",
    399: "LidCgmDataG7",
    404: "LidCgmStartSessionFsl2",
    405: "LidCgmStopSessionFsl2",
    406: "LidCgmJoinSessionFsl2",
    447: "LidCgmStopSessionG7",
    460: "LidCgmAlertActivatedFsl2",
    461: "LidCgmAlertClearedFsl2",
    81: "LidDailyBasal",
    48: "LidCarbsEntered",
    36: "LidUsbConnected",
    37: "LidUsbDisconnected",
}